demo-service/front/main.py
import os

from flask import Flask

from views import views

def create_app():
    app = Flask(__name__)
    app.register_blueprint(views)

    return app

if __name__ == "__main__":
    app = create_app()
    app.run(port=int(os.environ.get('FLASK_PORT', 5000)))

demo-service/front/views.py
import os

from dotenv import load_dotenv
from flask import (
    Blueprint,
    url_for,
    redirect,
    render_template,
    request,
)
import requests

views = Blueprint('views', __name__, url_prefix="")

load_dotenv()
API_ENDPOINT = os.environ.get('API_ENDPOINT')

@views.route('/')
def home():
    req = requests.get(os.path.join(API_ENDPOINT, 'posts'))
    if req.status_code == requests.codes.ok:
        posts = req.json()['posts']
        return render_template('home.html', posts=posts)

@views.route('/post/add', methods=['POST'])
def post_add():
    uploaded_file = request.files['file']
    files = {'file': (uploaded_file.filename, uploaded_file)}

    req = requests.post(os.path.join(API_ENDPOINT, 'posts'), files=files)
    if req.status_code == requests.codes.ok:
        return redirect(url_for('views.home'), code=302)

@views.route('/post/edit/<id_post>', methods=['POST'])
def post_edit(id_post):
    new_file = request.files['file']
    files = {'file': (new_file.filename, new_file)}

    req = requests.put(os.path.join(API_ENDPOINT, 'posts', id_post), files=files)
    if req.status_code == requests.codes.ok:
        return redirect(url_for('views.home'), code=302)

@views.route('/post/delete/<id_post>')
def post_delete(id_post):
    req = requests.delete(os.path.join(API_ENDPOINT, 'posts', id_post))
    if req.status_code == requests.codes.ok:
        return redirect(url_for('views.home'), code=302)

@views.route('/post/<id_post>/comment/add', methods=['POST'])
def comment_add(id_post):
    req = requests.post(
        os.path.join(API_ENDPOINT, 'posts', id_post, 'comments'),
        json={'comment': request.form['comment']}
    )
    if req.status_code == requests.codes.ok:
        return redirect(url_for('views.home'), code=302)

@views.route('/comment/edit/<id_comment>', methods=['POST'])
def comment_edit(id_comment):
    req = requests.put(
        os.path.join(API_ENDPOINT, 'comments', id_comment),
        json={'comment': request.form['comment']}
    )
    if req.status_code == requests.codes.ok:
        return redirect(url_for('views.home'), code=302)

@views.route('/comment/delete/<id_comment>')
def comment_delete(id_comment):
    req = requests.delete(os.path.join(API_ENDPOINT, 'comments', id_comment))
    if req.status_code == requests.codes.ok:
        return redirect(url_for('views.home'), code=302)

demo-service/front/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Instagram v2</title>
    <base href="/" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <style>
      i.fas.fa-trash-alt {
        color: black;
      }
      i.fas.fa-trash-alt:hover {
        color: black;
      }
      i.fas.fa-trash-alt, i.fas.fa-pencil-alt {
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="row card-columns">
        {% for post in posts %}
            <div class="col-lg-4">
                <div class="card">
                    <img class="card-img-top" id="content-post-{{post.id}}" src="{{post.filename}}"></img>
                    <div class="card-body">
                    {% for comment in post.comments %}
                        <div class="mb-3">
                            <span id="content-comment-{{comment.id}}">
                                {{comment.comment}}
                            </span>
                            <form method="post" action="{{ url_for('views.comment_edit', id_comment=comment.id) }}" id="form-edit-comment-{{comment.id}}" style="display: none;" >
                            <div class="input-group">
                                <input name="comment" type="text" class="form-control" placeholder="Comment" value="{{comment.comment}}" required />
                                <div class="input-group-append">
                                    <button class="btn btn-primary button" type="submit">
                                        <i class="fas fa-check"></i>
                                    </button>
                                </div>
                            </div>
                            </form>
                            <span class="float-right">
                                <a href="{{ url_for('views.comment_delete', id_comment=comment.id) }}"><i class="fas fa-trash-alt"></i></a>
                            </span>
                            <span class="float-right">
                                <i class="fas fa-pencil-alt toggle-edit-comment" id="toggle-edit-comment-{{comment.id}}"></i>
                            </span>
                            <br />
                        </div>
                    {% endfor %}

                    <form method="post" action="{{ url_for('views.comment_add', id_post=post.id) }}" >
                        <div class="input-group">
                        <input name="comment" type="text" class="form-control" placeholder="Comment" required />
                        <div class="input-group-append">
                            <button class="btn btn-primary button" type="submit">
                                <i class="fas fa-plus"></i>
                            </button>
                        </div>
                        </div>
                    </form>

                    <form method="post" action="{{ url_for('views.post_edit', id_post=post.id) }}" id="form-edit-post-{{post.id}}" enctype="multipart/form-data" style="display: none;" >
                        <div class="input-group">
                        <input name="file" type="file" class="form-control" required />
                        <div class="input-group-append">
                            <button class="btn btn-primary button" type="submit">
                                <i class="fas fa-check"></i>
                            </button>
                        </div>
                        </div>
                    </form>
                    </div>

                    <div class="card-footer">
                        <a href="{{ url_for('views.post_delete', id_post=post.id) }}"><i class="fas fa-trash-alt"></i></a>
                        <i class="fas fa-pencil-alt toggle-edit-post" id="toggle-edit-post-{{post.id}}"></i>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="col-lg-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Add a post</h5>
              <form method="post" action="{{ url_for('views.post_add') }}" enctype="multipart/form-data">
                <div class="input-group">
                  <input name="file" type="file" class="form-control" required />
                  <div class="input-group-append">
                    <button class="btn btn-primary button" type="submit">
                        <i class="fas fa-plus"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript">
      $(() => {
        $("i.toggle-edit-comment").click((event) => {
          let $element = $(event.target);
          let [id_comment] = $element.attr('id').split('-').slice(-1);
          $(`form#form-edit-comment-${id_comment}`).toggle();
          $(`span#content-comment-${id_comment}`).toggle();
        });

        $("i.toggle-edit-post").click((event) => {
          let $element = $(event.target);
          let [id_form] = $element.attr('id').split('-').slice(-1);
          $(`form#form-edit-post-${id_form}`).toggle();
        });
      });
    </script>
  </body>
</html>